<!DOCTYPE html>
<!--
Copyright (c) 2013 Samsung Electronics Co., Ltd.

Licensed under the Apache License, Version 2.0 (the License);
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Authors:
        Krzysztof Lachacz <k.lachacz@samsung.com>

-->

<html>

<head>
<title>CallHistory_removeBatch_with_errorCallback</title>
<script src="support/unitcommon.js"></script>
<script src="support/callcommon.js"></script>
</head>

<body>
<div id="log"></div>
<script type="text/javascript">
//==== TEST: CallHistory_removeBatch_with_errorCallback
//==== LABEL Check if removeBatch called with optional errorCallback works as expected
//==== EXECUTION_TYPE manual
//==== SPEC Tizen Web API:Social:Callhistory:CallHistory:removeBatch M
//==== SPEC_URL https://developer.tizen.org/help/topic/org.tizen.web.device.apireference/tizen/callhistory.html
//==== TEST_CRITERIA MOA MAST
//==== PRE Make an existence call history

setup({timeout: 90000});

var t = async_test(document.title, {timeout: 90000}),
    findSuccess, findError, removeBatchSuccess, removeBatchError,
    findAfterSuccess, findAfterError;

t.step(function () {
    findAfterError = t.step_func(function (error) {
        assert_unreached("find() after error callback invoked: name: " + error.name + ", msg: " + error.message);
    });

    findAfterSuccess = t.step_func(function (results) {
        assert_type(results, "array", "Results should be an array");
        assert_equals(results.length, 0, "delete a list of call history entries failed");
        t.done();
    });

    removeBatchSuccess = t.step_func(function () {
        tizen.callhistory.find(findAfterSuccess, findAfterError);
    });

    removeBatchError = t.step_func(function (error) {
        assert_unreached("removeBatch() error callback invoked: name: " + error.name + ", msg: " + error.message);
    });

    findError = t.step_func(function (error) {
        assert_unreached("find errorCallback called: " + error.name + " with message: " + error.message);
    });

    findSuccess = t.step_func(function (results) {
        assert_type(results, "array", "Results should be an array");
        assert_true(results.length > 0, "Call is not found in the history.");
        tizen.callhistory.removeBatch(results, removeBatchSuccess, removeBatchError);
    });

    tizen.callhistory.find(findSuccess, findError);
});

</script>
</body>
</html>
