<!DOCTYPE html>
<!--
Copyright (c) 2013 Samsung Electronics Co., Ltd.

Licensed under the Apache License, Version 2.0 (the License);
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.


Authors:
        Jakub Siewierski <j.siewierski@samsung.com>

-->
<html>
<head>
<title>MessageService_email_sendMessage_successCallback_invalid_cb</title>
<script src="support/unitcommon.js"></script>
<script src="support/messaging_common.js"></script>
</head>

<body>
<div id="log"></div>
<script>
//==== TEST: MessageService_email_sendMessage_successCallback_invalid_cb
//==== LABEL Check if MessageService.sendMessage method throws exception when successCallback is invalid (email)
//==== PRIORITY: P2
//==== SPEC Tizen Web API:Communication:Messaging:MessageService:sendMessage M
//==== SPEC_URL https://developer.tizen.org/help/topic/org.tizen.web.device.apireference/tizen/messaging.html
//==== ONLOAD_DELAY 300
//==== TIMEOUT 300
//==== TEST_CRITERIA MTCB
setup({timeout: 300000});

var t = async_test(document.title, {timeout: 300000}),
    serviceSuccess, serviceError, message,
    sendError, invalidSuccessCallback, exceptionName = "TypeMismatchError";

t.step(function () {
    invalidSuccessCallback = {
        onsuccess: t.step_func(function (recipients) {
            assert_unreached("Invalid success callback invoked");
        })
    };

    sendError = t.step_func(function (error) {
        assert_unreached("Error callback invoked, name:" + error.name + ", msg:" + error.message);
    });

    serviceSuccess = t.step_func(function (service) {

        message = createSimpleMessageTo(TEST_EMAIL_RECIPIENT_2);

        assert_throws(
            { name: exceptionName },
            function () {
                service.sendMessage(message, invalidSuccessCallback, sendError);
            },
            exceptionName + " should be thrown - invalid success callback."
        );

        t.done();
    });

    serviceError = t.step_func(function (error) {
        assert_unreached("getMessageServices() error callback: name:" + error.name + ", msg:" + error.message);
    });

    getEmailService(t, serviceSuccess, serviceError);
});

</script>
</body>
</html>
