<!DOCTYPE html>
<!--
Copyright (c) 2013 Samsung Electronics Co., Ltd.

Licensed under the Apache License, Version 2.0 (the License);
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.


Authors:
        Tomasz Paciorek <t.paciorek@samsung.com>

-->
<html>
<head>
<title>ContactManager_updateBatch_errorCallback_invalid_cb</title>
<meta charset="utf-8"/>
<script type="text/javascript" src="support/unitcommon.js"></script>
</head>

<body>
<div id="log"></div>
<script>
//==== TEST: ContactManager_updateBatch_errorCallback_invalid_cb
//==== LABEL Check argument ContactManager updateBatch errorCallback validation - use {onerror: function (){}}
//==== PRIORITY: P2
//==== SPEC Tizen Web API:Social:Contact:ContactManager:updateBatch M
//==== SPEC_URL https://developer.tizen.org/help/topic/org.tizen.web.device.apireference/tizen/contact.html
//==== TEST_CRITERIA MTCB
var t = async_test(document.title), contact1, contact2, addressbook, updateBatchSuccess, getPerson1, getPerson2,
    incorrectCallback, exceptionName = "TypeMismatchError";
t.step(function () {
    contact1 = new tizen.Contact({
        name: new tizen.ContactName({
            firstName: "Jeffrey",
            lastName: "Hyman"
        })
    });

    contact2 = new tizen.Contact({
        name: new tizen.ContactName({
            firstName: "Elton",
            lastName: "John"
        })
    });
    incorrectCallback = {
        onerror: t.step_func(function (error) {
            assert_unreached("Invalid errorCallback invoked: " + error.name + ": " + error.message);
        })
    };
    addressbook = tizen.contact.getDefaultAddressBook();
    addressbook.add(contact1);
    addressbook.add(contact2);
    getPerson1 = tizen.contact.get(contact1.personId);
    getPerson2 = tizen.contact.get(contact2.personId);
    getPerson1.isFavorite = true;
    getPerson2.isFavorite = true;
    updateBatchSuccess = t.step_func(function (persons) {
        assert_unreached("Invalid updateBatchSuccess invoked. Persons = " + persons);
    });
    assert_throws({name: exceptionName},
        function () {
            tizen.contact.updateBatch([getPerson1, getPerson2], updateBatchSuccess, incorrectCallback);
        }, exceptionName + " should be thrown - given incorrect error callback.");
    addressbook.remove(contact1.id);
    addressbook.remove(contact2.id);
    t.done();
});

</script>
</body>
</html>
